-- AlterTable
ALTER TABLE `NFT` MODIFY `transactions` INTEGER NOT NULL DEFAULT 0,
    MODIFY `fee` INTEGER NOT NULL DEFAULT 600,
    MODIFY `closed` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `buyout` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `asset_claimed` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `bonus_tickets` INTEGER NOT NULL DEFAULT 0,
    MODIFY `tickets_bought` INTEGER NOT NULL DEFAULT 0,
    MODIFY `tokens_claimed` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `total_tickets` INTEGER NOT NULL DEFAULT 0;
