/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainABI } from "./MainABI";
export * as factories from "./factories";
export { MainABI__factory } from "./factories/MainABI__factory";
